[project]
name = 'Supply-Chain-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.payment-escrow]
path = 'contracts/payment-escrow.clar'
clarity_version = 2
epoch = 2.5

[contracts.product-tracking]
path = 'contracts/product-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.quality-control]
path = 'contracts/quality-control.clar'
clarity_version = 2
epoch = 2.5

[contracts.supplier-verification]
path = 'contracts/supplier-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
